/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

module.exports = [
  '$eq',
  '$gt',
  '$gte',
  '$in',
  '$lt',
  '$lte',
  '$ne',
  '$nin',
  '$and',
  '$not',
  '$nor',
  '$or',
  '$exists',
  '$type',
  '$expr',
  '$jsonSchema',
  '$mod',
  '$regex',
  '$text',
  '$where',
  '$geoIntersects',
  '$geoWithin',
  '$near',
  '$nearSphere',
  '$all',
  '$elemMatch',
  '$size',
  '$bitsAllClear',
  '$bitsAllSet',
  '$bitsAnyClear',
  '$bitsAnySet',
  '$',
  '$elemMatch',
  '$meta',
  '$slice',
  '$comment',
  '$rand',
];
